### ISSUE TITLE
[Android] Empty seed words when creating a wallet

### ISSUE THREAD

**Issue by ChrisEbner** [lightninglabs/lightning-app#1206] opened 2019-06-21 05:53 UTC
### Description
Android shows empty seed words reproducibly, like #1174 

### Steps to reproduce the behavior
Choose create a new wallet on App startup. Go back. Choose recover an existing wallet. Go back. Choose create a new wallet. Seed words will be empty.

### Expected behavior
Create a new random seed whenever Create a new wallet is pressed on startscreen.

### Actual behavior
See above.

### Screenshot and/or logs if applicable
![Screenshot_20190620-140126_Lightning](https://user-images.githubusercontent.com/6430561/59900729-5ee95300-93f9-11e9-9bee-7fd9c8193029.jpg)

**Comment by MichelKansou** [comment] 2019-06-24 13:12
I found and fixed the bug in my PR https://github.com/lightninglabs/lightning-app/pull/1212

**Comment by tanx** [comment] 2019-06-28 18:20
Closing as duplicate of #1174

**Closed by tanx** 2019-06-28 18:20 UTC
