### ISSUE TITLE
iOS stuck at loading network

### ISSUE THREAD

**Issue by joachimneumann** [lightninglabs/lightning-app#970] opened 2019-02-13 04:37 UTC
version 0.0.14:
from time to time the iOS app is stuck at loading network (see screenshot). Repeatedly killing the app and restarting does not resolve this issue, but after rebooting the iPhone the app starts normally.

![img_4470](https://user-images.githubusercontent.com/5642225/52687175-0b4d9100-2f51-11e9-8e07-e12a3a08e700.PNG)

**Comment by molxyz** [comment] 2019-02-13 22:54
I'm also having this issue with v0.0.14.

**Comment by tanx** [comment] 2019-02-19 06:44
Duplicate of #888

**Closed by tanx** 2019-02-19 06:44 UTC
