### ISSUE TITLE
Wallet app doesn't initialize after fingerprint / PIN input

### ISSUE THREAD

**Issue by DE4DCATBOUNCE** [lightninglabs/lightning-app#1211] opened 2019-06-23 19:07 UTC
### Description
Wallet stopped initializing. It worked after installing and adding some balance. It stopped working while I was trying to figure out how it works. After adding balance, a channel was opened automatically. After closing it, another channel opened right away, this happened multiple times. Then I disabled Autopilot. App stopped starting when trying to close a channel, last message visible - PENDING FORCED CLOSING.
Worst thing is, I deposited 10x the amount I intended to - mistyped the amount in sats.

### Steps to reproduce the behavior
See attached video below.

### Expected behavior
Starting.

### Actual behavior
Not starting. Fails to load, shows INVALID PASSWORD message.

### Screenshot and/or logs if applicable

video here - https://we.tl/t-MXp8X5WuX2

**Comment by connors2015** [comment] 2019-06-24 19:05
I can recreate the same error on Android. Everything worked properly until I disabled autopilot and closed the app.

**Comment by hikedev** [comment] 2019-06-30 12:03
I have the same problem that the app will print an INVALID PASSWORD message when I did disable the autopilot. Reinstalling and restoring the wallet will crash the app when syncing.

Is there any way to get the channel state on android and export it to the desktop version?

**Comment by exfrog** [comment] 2019-07-09 17:10
I am having the same problem.  installed yesterday, funded wallet, channel opened via autopilot.  closed channel (pending), closed app.
now when i enter the app, it asks for my pin, and prints invalid password on along the top of the app.  if i enter the wrong pin, it presents a pop-up saying invalid pin.  if i enter the correct pin, i get the invalid password message along the top of the app.  I am 100% certain i have the pin correct (exemplified by the different error when i use the wrong pin vs the right pin...)

**Comment by tanx** [comment] 2019-07-09 19:36
Duplicate of https://github.com/lightninglabs/lightning-app/issues/967

**Closed by tanx** 2019-07-09 19:36 UTC
