### ISSUE TITLE
Channel shows as pending, but allows sends

### ISSUE THREAD

**Issue by alexbosworth** [lightninglabs/lightning-app#657] opened 2018-09-11 15:47 UTC
### Description

I have one channel that can be used for sending, but in the interface it is marked as pending and the funds are marked as depositing.

### Steps to reproduce the behavior

This channel was initiated a long time ago and it briefly flashed as confirmed in the interface but then went back to pending

### Expected behavior

Channels that can be sent through should be marked as open

### Actual behavior

The pending channel balance changes as if it were open, but it's still pending

**Comment by Roasbeef** [comment] 2018-09-11 23:26
If you hit lnd on the cli, does it still show as pending? Also if you navigated to/from that page in the app, did it refresh properly?

**Comment by alexbosworth** [comment] 2018-09-11 23:30
It moved out of pending mode after this

I think I know why this happens, that the App shows channels as pending in that they don't have 6 confs, but a channel can be used for spending at 3 confs?

**Comment by erkarl** [comment] 2018-09-12 08:58
@alexbosworth for me it shows the channel as open when there are 3 confirmations (channels view). "Pending Deposit" (derived from `WalletBalance->total_balance` + ``ChannelBalance->pending_open_balance`) on the home screen seems to also be in sync with LND.

Test outputs on simnet when manually opening the channel:
# BEFORE CHANNEL OPEN
```
WALLETBALANCE: "total_balance": "1999914897554",
CHANNELBALANCE: "pending_open_balance": "0"
PENDING DEPOSIT LND: 1999914897554
PENDING DEPOSIT UI: "1,999,914,897,554"
```

# 0 CONF
```
WALLETBALANCE: "total_balance": "1999908889917",
CHANNELBALANCE: "pending_open_balance": "5990950"
PENDING DEPOSIT LND: 1999908889917 + 5990950 = 1,999,914,880,867
PENDING DEPOSIT UI: "1,999,914,880,867"
```

# 1 CONF
```
WALLETBALANCE: "total_balance": "1999908889917",
CHANNELBALANCE: "pending_open_balance": "5990950"
PENDING DEPOSIT LND: 1999908889917 + 5990950 = 1,999,914,880,867
PENDING DEPOSIT UI: "1,999,914,880,867"
```

# 2 CONF
```
WALLETBALANCE: "total_balance": "1999908889917",
CHANNELBALANCE: "pending_open_balance": "5990950"
PENDING DEPOSIT LND: 1999908889917 + 5990950 = 1,999,914,880,867
PENDING DEPOSIT UI: "1,999,914,880,867"
```

# 3 CONF
```
WALLETBALANCE: "total_balance": "1999908889917",
CHANNELBALANCE: "pending_open_balance": "0"
PENDING DEPOSIT LND: 1999908889917 = 1,999,908,889,917
PENDING DEPOSIT UI: "1,999,908,889,917"
```

**Comment by erkarl** [comment] 2018-09-12 11:42
I was able to get into a similar situation on my Windows 10 test machine using `0.2.1-alpha`. The channel shows up as `pending-open`, but the funding transaction [52bd3c2c2e4c42cff7d7eb3e989d35cc0d8f6276a2e4e5bbbf3f301d1edb277d](https://testnet.smartbit.com.au/tx/52bd3c2c2e4c42cff7d7eb3e989d35cc0d8f6276a2e4e5bbbf3f301d1edb277d) has 140+ confirmations.

![screen shot 2018-09-12 at 14 34 13](https://user-images.githubusercontent.com/1056569/45422522-19913b80-b699-11e8-9741-b717c0871aad.png)

I'm unable to access LND via `lncli` at this point because of:
```
C:\Users\AR\AppData\Roaming\lightning-app>lncli --rpcserver=localhost:10016 --macaroonpath=lnd/data/chain/bitcoin/testnet/admin.macaroon --tlscertpath=lnd/tls.cert getinfo
[lncli] rpc error: code = Internal desc = connection error: desc = "transport: authentication handshake failed: read tcp 127.0.0.1:55283->127.0.0.1:10016: wsarecv: An existing connection was forcibly closed by the remote host."
```

[lnd-logs.zip](https://github.com/lightninglabs/lightning-app/files/2374925/lnd-logs.zip)

**Comment by erkarl** [comment] 2018-09-13 10:52
Quick update on my Windows node mentioned above. Eventually the channels became `open`.

**Comment by garryclawson** [comment] 2018-09-14 19:43
I am in a similar position using 0.2.1-alpha on a Mac 10.13.6. since 12th Sep. The channel shows as pending-open, but the funding transaction ee8edd04a2511c684bd9cf5fb99c9b29f1730a93f88d594f24cd82d49be7202f does not show confirmed. Several channels since have been successfully opened. Attached log files for ref.

[log.txt](https://github.com/lightninglabs/lightning-app/files/2384661/log.txt)

<img width="872" alt="channel openings" src="https://user-images.githubusercontent.com/42511133/45571601-a9341700-b85e-11e8-992e-27f9e3a30dc6.png">

**Comment by tanx** [comment] 2018-10-29 16:19
> I think I know why this happens, that the App shows channels as pending in that they don't have 6 confs, but a channel can be used for spending at 3 confs?

Yes. The funding transaction were previrously displayed as unconfirmed until 6 confs. This is now changed to 1. So this issue should be fixed.

**Closed by tanx** 2018-10-29 16:19 UTC
Labels: bug, ui
