### ISSUE TITLE
App should display which network it is connected to

### ISSUE THREAD

**Issue by cilphex** [lightninglabs/lightning-app#726] opened 2018-10-10 00:36 UTC
### Description

Lightning app is currently configured to operate on testnet, but if you don't catch this detail when downloading it, you might not know that.

It would be helpful for the app to display what network it is connected to (testnet or mainnet) during setup, and maybe also in settings.

### Steps to reproduce the behavior

Install lightning app

### Expected behavior

It should display the network it is connected to during initialization and in settings (or someplace that seems reasonable).

### Actual behavior

Network is not displayed anywhere

### Screenshot and/or logs if applicable

N/A

**Comment by tanx** [comment] 2019-03-13 04:40
Duplicate of #940

**Closed by tanx** 2019-03-13 04:40 UTC
