### ISSUE TITLE
historical closed channels aren't displayed in the UI

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/lightning-app#530] opened 2018-08-15 22:34 UTC
Atm, we show pending open, open, and pending closed channels. However, we don't show channels that have been _closed_ already. This is exposed via the `ClosedChannel` RPC: https://api.lightning.community/#closedchannels. Just as we show past on-chain transactions, we should also show past closed channels for the sake of record keeping, since it is after all financial data.

**Comment by tanx** [comment] 2018-08-16 13:59
Duplicate of https://github.com/lightninglabs/lightning-app/issues/507

**Closed by tanx** 2018-08-16 13:59 UTC
