### ISSUE TITLE
Channel Information, min channel capacity, information for work in progress

### ISSUE THREAD

**Issue by wdey** [lightninglabs/lightning-app#1095] opened 2019-05-01 08:13 UTC
Have 20'000 sat transferred; don't see any progress, although autopilot is enabled
- what is the min. amount of BTC that is needed to open a channel
- I assume, we open simply one channel which is private ?
- where can I see where this channel terminates (logs are rolling over)
- when a funding tx is pending, where can I find this information (logs are rolling over)
- in a paying tx, I can press confirm, but no error message in the UI, have to swtich to log.
Do I miss something ?

**Comment by tanx** [comment] 2019-05-09 23:02
Duplicate of #1074

**Closed by tanx** 2019-05-09 23:02 UTC
