### ISSUE TITLE
iOS initial syncing stopped

### ISSUE THREAD

**Issue by Jonbros01** [lightninglabs/lightning-app#942] opened 2019-02-08 09:16 UTC
The initial syncing stopped on iOS and didn’t progress for many hours. No error message was showing, just the blocks where not progressing. After a while I decided to kill the app and relaunched then it quickly completely sync

**Comment by bit-the-dust** [comment] 2019-02-08 12:52
Same with me. It may be a coincidence, but might have happened when the phone auto-locked or the app lost focus for a period.

Manually shutting down the app and re-opening re-started the download, but I have had to do this a couple of times now.

iOS 0.0.13 (13)

**Comment by bit-the-dust** [comment] 2019-02-08 12:57
May be a duplicate of https://github.com/lightninglabs/lightning-app/issues/903

**Comment by Jonbros01** [comment] 2019-02-08 13:14
This morning I got a black screen and a loading network and spinning wheel in the middle of the screen.

It never load beyond that screen.  I kill the app and restart and still do the same loading network.

Is the app have to connect to a server ?

**Comment by tanx** [comment] 2019-02-11 08:25
@Roasbeef any idea?

**Comment by Roasbeef** [comment] 2019-02-11 23:45
I think part of this may be that (discovered this recently), it's possible for a user to continue to "swipe left" and end up all the way back at the initial loading page, and then also the unlock page. From here, they aren't able to progress forwards. 

As for the syncing stall, hard to debug without any logs. Don't have an iPhone myself yet, so I can't easily try to reproduce this. A relevant question would be: 3g or wifi, or roaming between both? On the lnd end, for neutrino, we likely need to start enforcing more aggressive read/write timeouts on the socket. It may be the case that the TCP connection has died (because mobile), and we haven't yet detected it so we're trying to read something that'll never come through. 

Alternatively, it may be an issue with the cluster if it isn't using sticky TCP connections. Until we make the planned breaking neutrino level change, we should stick with the cluster. After that, we can relax it from "only connect to these nodes", to "connect to this node, and then whoever else".

**Comment by joachimneumann** [comment] 2019-02-13 03:46
Version 0.0.14: My App got stuck in the initial sync (block number did not increase) if I (a) close and re-open the app and (b) if I kill and restart the app. My only solution was to delete and re-install the app and let the initial sync finish without closing the app

**Comment by Roasbeef** [comment] 2019-02-13 23:39
We also realized 1/3 of the nodes we sync from (for this testnet alpha) were behind the chain and not syncing. As a result, if you got paired with this stuck now, then your app would just stick there until a restart that would maybe connect you to a lively node. We've fixed this since then.

**Comment by Jonbros01** [comment] 2019-02-14 01:52
Seem to have solve my syncing issues

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by tanx** [comment] 2019-04-25 08:47
This seems to be resolved in the current lnd master. Will be included in the next iOS release.

**Closed by tanx** 2019-04-25 08:47 UTC
Labels: bug, ios, lnd
