### ISSUE TITLE
iOS - Channel balance does not display correctly on home screen

### ISSUE THREAD

**Issue by molxyz** [lightninglabs/lightning-app#926] opened 2019-02-05 07:16 UTC
### Description
When fonts set on BOLD, this is how channel balance looks like on my iphone:

![image](https://user-images.githubusercontent.com/21127776/52258087-af995d00-28eb-11e9-8c94-3f8e0a8605db.png)

![image](https://user-images.githubusercontent.com/21127776/52258100-bf18a600-28eb-11e9-93d0-e37d6a255773.png)

When BOLD is taken off, one digit goes missing...

![image](https://user-images.githubusercontent.com/21127776/52258129-e7080980-28eb-11e9-8bbb-3bc53784b0d8.png)

Not much has changed on the balance, the total should be 113,310,625 sat.

**Comment by tanx** [comment] 2019-02-11 08:45
Duplicate of https://github.com/lightninglabs/lightning-app/issues/879

**Closed by tanx** 2019-02-11 08:45 UTC
