### ISSUE TITLE
minor: seed recovery process, move cursor/focus to next page

### ISSUE THREAD

**Issue by bryanvu** [lightninglabs/lightning-app#1027] opened 2019-03-20 01:07 UTC
### Description

When entering the seed during the seed recovery process, each new page of three words requires a mouse click in order to enter the next set of seed words. Ideally, the cursor would be moved automatically so that the seed can by typed quickly without using the mouse.

### Steps to reproduce the behavior

Open a new installation of Lightning App, select recover existing wallet. Enter the first page of words (tabbing to move between fields) press Enter. You will now need to click the mouse again to enter the next set of words.

### Expected behavior

Cursor moves automatically between pages.

### Actual behavior

Must click mouse again.

**Comment by tanx** [comment] 2019-03-20 09:56
Duplicate of #729

**Closed by tanx** 2019-03-20 09:56 UTC
