### ISSUE TITLE
Pending Deposit and Wallet Addcoin button

### ISSUE THREAD

**Issue by molxyz** [lightninglabs/lightning-app#636] opened 2018-09-08 03:03 UTC
Deposit transactions already have more than 6 confirmations but the wallet still says "Pending Deposit", and this doesn't change even after I restart the app.  Also, all of my channels aren't open, and the txid's can't be found on explorer. I guess because the wallet thinks it doesn't have any available coins.. 

Also, when I got to this screen I clicked on "Request", thinking it was the button to add coins to this wallet, because Bitcoin Core wallet has "Request payment". It took me a min or so to realize that the "Addcoin" button is at the top.  I think it'll be better if we can have this button larger and the feature more visible on this screen 

![pending deposit](https://user-images.githubusercontent.com/21127776/45249678-3b35a000-b2f2-11e8-84f9-efea36635005.png)

**Comment by erkarl** [comment] 2018-09-08 11:43
Think this behaviour is correct. Coins in your `walletbalance` are marked as "Pending deposit" because they are not yet usable for lightning payments. Once the autopilot funding transactions get confirmed it should show them where you currently have "0 SAT".

I agree, it's a little confusing and it took me a while to figure this out as well. I'm guessing it will cause confusion for many users.

**Comment by valentinewallace** [comment] 2018-09-09 22:03
Due to super-high testnet fees right now, sometimes channels can take 1+ days to successfully open/close. However, it's strange that you can't find your txids in a block explorer.

There's a bug in lnd right now where sometimes transactions don't broadcast at first, but restarting the app should cause the tx to rebroadcast. Have you tried restarting? and if that doesn't work, could you check the mempool for your transactions?

**Comment by tanx** [comment] 2018-09-10 07:34
> Think this behaviour is correct. Coins in your walletbalance are marked as "Pending deposit" because they are not yet usable for lightning payments. Once the autopilot funding transactions get confirmed it should show them where you currently have "0 SAT".

Yes. The `Pending Deposit` is a sum of your on-chain funds as well as any funds in pending channels. We do this to ensure the user that their funds are all there, but not yet available to off-chain transactions.

Re testnet... prealpha 31 includes a patch to increase fees for testnet. Hopefully this should speed up confirmation of channel funding transactions.

> I agree, it's a little confusing and it took me a while to figure this out as well. I'm guessing it will cause confusion for many users.

Yes, this might create confusion for advanced users who already understand the protocol details of how on-chain vs. off-chain works. However the working hypothesis for the app design is to target a more novice bitcoin user audience who isn't necessarily familiar with those details. So the high level semantics of `Pending Deposit` might be easier to understand. We're looking to test that hypothesis by doing UX research with the target user group after the release.

**Comment by tanx** [comment] 2018-09-12 12:45
Alright after talking with @roasbeef about this, the idea is to do some over-the-shoulder A/B testing with users for different solutions and see what works best. Some potential candidates:

1. Dynamic copy/label on the home screen for where `Pending Deposit` currently is, depending on state of channels/on-chain funds
2. Adding a third number on the home screen... so it would be open/pending/on-chain
3. Leaving the home screen as is and adding a fourth number for the on-chain balance in the summary at the top of the channels screen

We should test this with two user archetypes:

1. Advanced bitcoiners who might be a bit more familiar with lightning
2. Notice bitcoiners who are approaching lightning for the first time

**Comment by toxonaut** [comment] 2018-09-14 17:50
I've sent coins to my wallet. The transactions were shown on the transaction as soon as they were confirmed. However after 3 days the main screen still shows pending deposit and the balance is 0 BTC.

**Comment by Roasbeef** [comment] 2018-09-14 17:57
If you check the logs, do you see anything interesting? We're aware of this
issue and are working on a fix on the neutrino end, it should be packaged
with an update of the app that'll go out early next week. For now the
workaround is a restart of the application

On Sep 14, 2018 10:50 AM, "toxonaut" <notifications@github.com> wrote:

I've sent coins to my wallet. The transactions were shown on the
transaction as soon as they were confirmed. However after 3 days the main
screen still shows pending deposit and the balance is 0 BTC.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lightninglabs/lightning-app/issues/636#issuecomment-421435166>,
or mute the thread

**Comment by toxonaut** [comment] 2018-09-14 19:34
Thanks for the reply. Restarting does not help. I looked at the (long) log. Of interest could be the following:
lnd: 2018-09-14 21:31:53.716 [ERR] SRVR: unable to start server: Couldn't retrieve block 00000000000000150514af189482515a12649ec32ef5c12939bea877b3728bf4 from network
lnd: 2018-09-14 21:31:53.716 [INF] BTCN: Lost peer 104.155.159.141:18333 (outbound)
2018-09-14 21:31:53.717 [WRN] BTCN: No sync peer candidates available
lnd: 2018-09-14 21:31:53.767 [INF] BTCN: Block manager shutting down
2018-09-14 21:31:53.767 [INF] BTCN: Address manager shutting down
lnd: 2018-09-14 21:31:53.810 [INF] LTND: Shutdown complete
ERROR: lnd Error: Couldn't retrieve block 00000000000000150514af189482515a12649ec32ef5c12939bea877b3728bf4 from network

and then repeadedly:
ERROR: Getting channel balance failed
{
    "code": 14,
    "details": "Connect Failed",
    "metadata": {
        "_internal_repr": {}
    }
}

**Comment by bitcoinuser** [comment] 2018-09-29 02:43
Doesn't make sense have the (Pending Deposit)  information and the (balance 0) on main window if the user still didn't deposited any coin. This space can be better used to novices understand that they need deposit coins first.

**Closed** 2018-10-02 16:05 UTC
Labels: ux research needed
