### ISSUE TITLE
Activity timer spins endlessly after app has been in background a while - ios

### ISSUE THREAD

**Issue by weaklysubjective** [lightninglabs/lightning-app#946] opened 2019-02-08 17:53 UTC
### Description
App was launched. Allowed to sync. App was put on background and upon foregrounding, get confused and never finishes syncing. Dismiss and relaunch is the only choice at this point.

### Steps to reproduce the behavior
1) Launch 
2) Sync 
3) Background app 
4) Use other apps (not heavy hitting apps that will cause iOS to remove LL App from memory but some light apps so LL continues to stay memory resident) 
5) Suspend app and launch LL app into foreground
6) Activity spins and app doesn't progress to next view

### Expected behavior

For app to complete syncing and proceed normally or for LL app to relaunch itself

### Actual behavior
Activity spins and app doesn't proceed

**Comment by tanx** [comment] 2019-02-11 06:34
Duplicate of https://github.com/lightninglabs/lightning-app/issues/888

**Closed by tanx** 2019-02-11 06:34 UTC
