### ISSUE TITLE
Cannot withdraw on-chain funds (Fee Estimation Failed!)

### ISSUE THREAD

**Issue by vnumeris** [lightninglabs/lightning-app#1161] opened 2019-06-13 07:34 UTC
### Description
Withdrawal request for on-chain payment result in the error message "Fee estimation failed!" despite updating app to latest release (v0.5.2).

### Steps to reproduce the behavior
Select 'Pay', enter Bitcoin address, enter any amount to transfer. Pressing Next shows the error above.

### Expected behavior
Expected to be able to transfer BTC to any given address.

### Actual behavior
Can't transfer BTC to any address.

### Screenshot and/or logs if applicable
lnd: 2019-06-13 17:32:24.712 [WRN] BTCN: No peers replied to inv message for transaction 525eb967a0a0806e4208693283ccd81a17ac58c13940040b5d6c1603243d81cc
lnd: 2019-06-13 17:32:25.212 [WRN] BTCN: No peers replied to inv message for transaction d047b8956b59fe214fad5864c3a6c02706f4fc2dfc35679227640020e2421b30
lnd: 2019-06-13 17:32:25.712 [WRN] BTCN: No peers replied to inv message for transaction e9c1c4b72950f9883b7c007ea125622eecafc620602835ce454c50b2e8dc6a80
lnd: 2019-06-13 17:32:26.213 [WRN] BTCN: No peers replied to inv message for transaction 1ae56c2141f4cc9bb149d73fdae78b62a56b4994de2736dceeacd21798b34e4a
lnd: 2019-06-13 17:32:26.714 [WRN] BTCN: No peers replied to inv message for transaction 136880e484e16e787e4c5239d286616ddccf4f068fc0c3843dd5935ae664508d
lnd: 2019-06-13 17:32:27.214 [WRN] BTCN: No peers replied to inv message for transaction 0add4dc5c5cd76217abd0109fa763031d231b2fe93d5d0cd6279cc9700c6224d
lnd: 2019-06-13 17:32:27.715 [WRN] BTCN: No peers replied to inv message for transaction a087f64043b709527e8693f9854b74f8d195369f7117ddcc6574b0152962dc3f
lnd: 2019-06-13 17:32:28.215 [WRN] BTCN: No peers replied to inv message for transaction df5b3f9bd0a46878ffa4e3a6567269ad29078e01a319365511b5f5ad316eae30
lnd: 2019-06-13 17:32:28.715 [WRN] BTCN: No peers replied to inv message for transaction c9151c714f39016f018605fc94805139f07add5d4e9941ba4aa9a43eded4264d

**Comment by valentinewallace** [comment] 2019-06-28 00:24
Another user has reported this issue. @vnumeris This problem is fixed in lnd master and the fix is going to be in the next app update.

**Comment by domegabri** [comment] 2019-07-04 14:46
I am experiencing the same (Version 0.5.4-alpha (0.5.4-alpha.3851)) on macOS 10.14.4.
I get a fee estimation failed error for whatever amount I choose (max or higher).

**Comment by tanx** [comment] 2019-07-04 16:51
Several users have reported this. To clarify, is it reproducible every time or only during poor connectivity?

**Comment by domegabri** [comment] 2019-07-04 16:52
I can reproduce every time under good network conditions

**Comment by tanx** [comment] 2019-07-04 16:53
> I can reproduce every time under good network conditions

ok thank you.

**Comment by tanx** [comment] 2019-07-04 17:26
@domegabri does it still fail after the channel closing transaction has 3 confirmations?

**Comment by domegabri** [comment] 2019-07-04 17:42
Channel closing happened a while ago so yes. The weird thing is that I have a series of unconfirmed tx in my transaction list, all of the same amount, with 0 fees. Also, the max amount (clicking max when sending on-chain) is larger than what my real balance is supposed to be.

**Comment by Roasbeef** [comment] 2019-07-04 20:56
How much are you trying to send out?

**Comment by domegabri** [comment] 2019-07-06 09:55
< 5mBTC. I am getting the fee estimation error for basically any amount.

**Comment by mike360** [comment] 2019-07-10 21:11
Also experiencing this issue with any amount under good network conditions. Haven't been able to transfer to a BTC address at all.

**Comment by davidlosak** [comment] 2019-07-10 21:53
I am getting the fee estimation error since late May this year, once I closed all the open channels (0% on Lightning) and just wanted to send all the remaining funds from the app to a btc address on-chain. I am running it on Mac since April, at the time it was v0.5.1. Later I updated to v0.5.3 and today to v0.5.4, but the error is displayed always for any amount which I try to send. I have a stable network connection.

**Comment by Roasbeef** [comment] 2019-07-10 22:04
If you run this command (on mac), then try to send again, what shows up in the logs? 
```
lncli --lnddir=~/Library/Application\ Support/lightning-app/lnd/ --rpcserver=localhost:10006 debuglevel --level=LNWL=info,RPCS=trace,SWPR=trace
```

That will increase the debug level to try to get more information to see what's going on.

**Comment by davidlosak** [comment] 2019-07-11 20:04
@Roasbeef I cannot run this command as **lncli** cannot not be found in terminal bash. Note that I did not install lightning - just the standalone app ( Lightning-darwin-x64v0.5.4-alpha.dmg
from https://github.com/lightninglabs/lightning-app/releases ). I don't find lncli under ~/Library/Application Support/lightning-app/lnd neither under ./dist/mac/Lightning.app/ -- Where is it located?

**Comment by davidlosak** [comment] 2019-07-11 20:18
Does this help? (without running the mentioned command)

LOGS
m channel graph
lnd: 2019-07-11 22:11:33.565 [INF] CHDB: Pruned unconnected node 025451d21945ac1165fa9c691693a08d3242f1f4deeac8b4fe3cb100aa9d9b50a8 from channel graph
2019-07-11 22:11:33.565 [INF] CHDB: Pruned unconnected node 026dab73058af378074d41b2b4ee9b0e25284529d0be86fcd72ecbd37b298f4835 from channel graph
lnd: 2019-07-11 22:11:33.566 [INF] CHDB: Pruned unconnected node 03984d92cdc95dfc197c190f8d99af095089ce70e00757920a15625919e2f0dab5 from channel graph
2019-07-11 22:11:33.566 [INF] CHDB: Pruned unconnected node 02fcdb04f51d61dddc0481c10751173d523e3408ebe3a848a1d6cb34b1f5df6668 from channel graph
lnd: 2019-07-11 22:11:33.566 [INF] CHDB: Pruned unconnected node 02478b883ffaf17d6803d651e64a28376aa8ef24e0b25c9fb52f4cd7e57d85e5b1 from channel graph
lnd: 2019-07-11 22:11:33.566 [INF] CHDB: Pruned unconnected node 02aeadde2cd5b3776c7f53b783c6b7ccc5feeaf9c5355e8a382a0091e825d8d215 from channel graph
lnd: 2019-07-11 22:11:33.567 [INF] CHDB: Pruned unconnected node 03f48fc5acea5b3878ff216027f367762805f02feab11a038ea2d144b0a3eb8a38 from channel graph
lnd: 2019-07-11 22:11:33.567 [INF] CHDB: Pruned unconnected node 036d5f176ad838a3dcc76361762c64d452bea769a539fd55c83864843af6a7b9c4 from channel graph
lnd: 2019-07-11 22:11:33.567 [INF] CHDB: Pruned unconnected node 03ca0d8ffa217f86a5787b9a9d1310998b6b8c4ec60d3cd1c785fe96c42dfd7fdd from channel graph
2019-07-11 22:11:33.567 [INF] CHDB: Pruned unconnected node 03ddd83f5034c9312a01950bbaddc8df127ddc52840a989a54c8672124e883816f from channel graph
2019-07-11 22:11:33.567 [INF] CHDB: Pruned unconnected node 0378e79d12cbd07ea03d76a0967eeb9dcdbaede1750cb4b9781db78cd3e8eb5137 from channel graph
2019-07-11 22:11:33.567 [INF] CHDB: Pruned unconnected node 031a0f4914422ba04d12b3a75c22b500ccb2e6ea85eb6cc476b045653019d38b20 from channel graph
lnd: 2019-07-11 22:11:33.568 [INF] CHDB: Pruned unconnected node 02310841b34230632b2e8185f9429dbf27a463270cf049a66ce2d56b524b283b6d from channel graph
lnd: 2019-07-11 22:11:33.568 [INF] CHDB: Pruned unconnected node 024844abb8efc3262539fffb66cbb46282324894212a13bb5b4c7cae96744e5a97 from channel graph
2019-07-11 22:11:33.568 [INF] CHDB: Pruned unconnected node 027728206f6840e6e88de827c6c2ab609875dbb273186c080a72c78c4a31619e4d from channel graph
2019-07-11 22:11:33.568 [INF] CHDB: Pruned unconnected node 0370805207c6db1c09528c20db0e32898bf8ff9116e47803a60b63b6d54705f904 from channel graph
2019-07-11 22:11:33.568 [INF] CHDB: Pruned 39 unconnected nodes from the channel graph
lnd: 2019-07-11 22:11:33.583 [INF] CHBU: Starting chanbackup.SubSwapper
2019-07-11 22:11:33.583 [INF] INVC: New invoice subscription client: id=0
lnd: 2019-07-11 22:11:33.583 [INF] CMGR: Server listening on 127.0.0.1:10016
lnd: 2019-07-11 22:11:33.596 [INF] CHBU: Updating backup file at /Users/deyw/Library/Application Support/lightning-app/lnd/data/chain/bitcoin/mainnet/channel.backup
2019-07-11 22:11:33.596 [INF] SRVR: Initializing peer network bootstrappers!
lnd: 2019-07-11 22:11:33.597 [INF] SRVR: Creating DNS peer bootstrapper with seeds: [[nodes.lightning.directory soa.nodes.lightning.directory] [lseed.bitcoinstats.com ]]
lnd: 2019-07-11 22:11:33.598 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory] [lseed.bitcoinstats.com ]]
lnd: 2019-07-11 22:11:33.601 [INF] CHBU: Swapping old multi backup file from /Users/deyw/Library/Application Support/lightning-app/lnd/data/chain/bitcoin/mainnet/temp-dont-use.backup to /Users/deyw/Library/Application Support/lightning-app/lnd/data/chain/bitcoin/mainnet/channel.backup
lnd: 2019-07-11 22:11:33.987 [INF] SRVR: Established connection to: 02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71@139.99.123.188:9735
2019-07-11 22:11:33.987 [INF] SRVR: Finalizing connection to 02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71@139.99.123.188:9735, inbound=false
lnd: 2019-07-11 22:11:34.165 [INF] SRVR: Pruning peer 02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71 from persistent connections, number of open channels is now zero
lnd: 2019-07-11 22:11:34.166 [INF] SRVR: Negotiated chan series queries with 02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71
lnd: 2019-07-11 22:11:34.167 [INF] DISC: Creating new GossipSyncer for peer=02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71
2019-07-11 22:11:34.167 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): requesting new chans from height=0 and 4294967295 blocks after
lnd: 2019-07-11 22:11:34.783 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): buffering chan range reply of size=8000
lnd: 2019-07-11 22:11:34.956 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): buffering chan range reply of size=8000
lnd: 2019-07-11 22:11:34.967 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): buffering chan range reply of size=8000
lnd: 2019-07-11 22:11:35.135 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): buffering chan range reply of size=8000
lnd: 2019-07-11 22:11:35.142 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): buffering chan range reply of size=5639
2019-07-11 22:11:35.142 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): filtering through 37639 chans
lnd: 2019-07-11 22:11:35.592 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): starting query for 456 new chans
2019-07-11 22:11:35.592 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): querying for 456 new channels
lnd: 2019-07-11 22:11:48.960 [INF] DISC: Obtained 3 addrs to bootstrap network with
lnd: 2019-07-11 22:11:49.017 [INF] SRVR: Established connection to: 029e6c271c6387c7d8dbcdcb5f91ca31f6ce2bf1f1bc681778eefb73fcda5785bb@5.39.85.34:9735
2019-07-11 22:11:49.017 [INF] SRVR: Finalizing connection to 029e6c271c6387c7d8dbcdcb5f91ca31f6ce2bf1f1bc681778eefb73fcda5785bb@5.39.85.34:9735, inbound=false
lnd: 2019-07-11 22:11:49.043 [INF] SRVR: Pruning peer 029e6c271c6387c7d8dbcdcb5f91ca31f6ce2bf1f1bc681778eefb73fcda5785bb from persistent connections, number of open channels is now zero
2019-07-11 22:11:49.043 [INF] SRVR: Negotiated chan series queries with 029e6c271c6387c7d8dbcdcb5f91ca31f6ce2bf1f1bc681778eefb73fcda5785bb
lnd: 2019-07-11 22:11:49.045 [INF] DISC: Creating new GossipSyncer for peer=029e6c271c6387c7d8dbcdcb5f91ca31f6ce2bf1f1bc681778eefb73fcda5785bb
lnd: 2019-07-11 22:11:49.047 [INF] SRVR: Established connection to: 02a9acaa1500f1e9f756118b2a7ed0447e6ca991ee6a9cbfe753d88f0dfae8cbe9@5.10.5.22:9735
lnd: 2019-07-11 22:11:49.048 [INF] SRVR: Finalizing connection to 02a9acaa1500f1e9f756118b2a7ed0447e6ca991ee6a9cbfe753d88f0dfae8cbe9@5.10.5.22:9735, inbound=false
lnd: 2019-07-11 22:11:49.066 [INF] SRVR: Established connection to: 030b9d7e80a4cc1df746bfa4b79574d2334670d8b817ded494b98cd996f6ede960@91.64.55.209:9735
2019-07-11 22:11:49.066 [INF] SRVR: Finalizing connection to 030b9d7e80a4cc1df746bfa4b79574d2334670d8b817ded494b98cd996f6ede960@91.64.55.209:9735, inbound=false
lnd: 2019-07-11 22:11:49.092 [INF] SRVR: Pruning peer 02a9acaa1500f1e9f756118b2a7ed0447e6ca991ee6a9cbfe753d88f0dfae8cbe9 from persistent connections, number of open channels is now zero
2019-07-11 22:11:49.092 [INF] SRVR: Negotiated chan series queries with 02a9acaa1500f1e9f756118b2a7ed0447e6ca991ee6a9cbfe753d88f0dfae8cbe9
lnd: 2019-07-11 22:11:49.096 [INF] DISC: Creating new GossipSyncer for peer=02a9acaa1500f1e9f756118b2a7ed0447e6ca991ee6a9cbfe753d88f0dfae8cbe9
lnd: 2019-07-11 22:11:49.201 [INF] SRVR: Pruning peer 030b9d7e80a4cc1df746bfa4b79574d2334670d8b817ded494b98cd996f6ede960 from persistent connections, number of open channels is now zero
lnd: 2019-07-11 22:11:49.202 [INF] SRVR: Negotiated chan series queries with 030b9d7e80a4cc1df746bfa4b79574d2334670d8b817ded494b98cd996f6ede960
lnd: 2019-07-11 22:11:49.205 [INF] DISC: Creating new GossipSyncer for peer=030b9d7e80a4cc1df746bfa4b79574d2334670d8b817ded494b98cd996f6ede960
lnd: 2019-07-11 22:11:53.982 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): no more chans to query
lnd: 2019-07-11 22:11:53.982 [INF] DISC: GossipSyncer(030b9d7e80a4cc1df746bfa4b79574d2334670d8b817ded494b98cd996f6ede960): applying gossipFilter(start=2019-07-11 22:11:53.98262 +0200 CEST m=+39.103331128, end=2155-08-18 03:40:08.98262 +0100 CET m=+4294967334.103331128)
2019-07-11 22:11:53.983 [INF] DISC: GossipSyncer(02b775b4d8e51f60914853ae55a2cf38a254163bb2639cd15dc0dd419612c43b71): applying gossipFilter(start=2019-07-11 22:11:53.983281 +0200 CEST m=+39.103991163, end=2155-08-18 03:40:08.983281 +0100 CET m=+4294967334.103991163)
lnd: 2019-07-11 22:11:53.984 [INF] DISC: GossipSyncer(02a9acaa1500f1e9f756118b2a7ed0447e6ca991ee6a9cbfe753d88f0dfae8cbe9): applying gossipFilter(start=2019-07-11 22:11:53.983916 +0200 CEST m=+39.104626239, end=2155-08-18 03:40:08.983916 +0100 CET m=+4294967334.104626239)
lnd: 2019-07-11 22:12:33.583 [INF] CRTR: Processed channels=456 updates=908 nodes=206 in last 1m0.000624721s
lnd: 2019-07-11 22:13:02.928 [INF] DISC: Broadcasting 1570 new announcements in 18 sub batches
lnd: 2019-07-11 22:13:33.584 [INF] CRTR: Processed channels=0 updates=3 nodes=0 in last 1m0.000691715s
lnd: 2019-07-11 22:14:32.928 [INF] DISC: Broadcasting 5 new announcements in 1 sub batches
lnd: 2019-07-11 22:14:33.587 [INF] CRTR: Processed channels=0 updates=2 nodes=0 in last 1m0.00313142s
lnd: 2019-07-11 22:15:33.587 [INF] CRTR: Processed channels=0 updates=5 nodes=0 in last 1m0.000603039s
lnd: 2019-07-11 22:16:02.927 [INF] DISC: Broadcasting 6 new announcements in 1 sub batches
lnd: 2019-07-11 22:16:33.584 [INF] CRTR: Processed channels=0 updates=1 nodes=0 in last 59.99722631s

**Comment by valentinewallace** [comment] 2019-07-11 20:47
@davidlosak could you install `lncli` by downloading the darwin release from the bottom of the page [here](https://github.com/lightningnetwork/lnd/releases/tag/v0.7.0-beta)? If you need help please contact us on [slack](https://lightningcommunity.slack.com)

**Comment by davidlosak** [comment] 2019-07-11 22:00
ok, I have sent the log on slack in the #lightning-app channel

**Comment by CandleHater** [comment] 2019-07-19 10:56
Same up here using Android with a Pixel 3 XL. After the bug https://github.com/lightninglabs/lightning-app/issues/1241 got fixed, I force closed all channels and waited for the lock time. Now when I try to send the funds on chain and select "Max" on the Bitcoin payment page, I get an error with "Fee estimation failed!" when I press the "Next" button.

![screenshot-1563533509182](https://user-images.githubusercontent.com/50766841/61530542-9bbe5f00-aa24-11e9-97af-d914ce500fe5.jpg)

**Comment by tanx** [comment] 2019-08-13 08:43
#1292 adds a more detailed error message in the notification bar. This will be rolled out in `0.2.2`.

**Closed** 2019-09-24 10:57 UTC
Labels: android, bug, desktop, ios, lnd

**Comment by domegabri** [comment] 2019-10-14 10:11
problem persists. can't withdraw because balance looks wrong and I still see a bunch of unconfirmed txs. In particular the one containing my only utxo shows up as unconfirmed while its actually confirmed
