### ISSUE TITLE
 Lightning payment failed! +  Fee estimation failed!

### ISSUE THREAD

**Issue by vamp111** [lightninglabs/lightning-app#1135] opened 2019-06-04 18:24 UTC
LND Desktop latest version

initiated an on-chain paymet, got error: fee estimation failed
initiated an off-chain payment, got error: Ln payment failed
logs: https://pastebin.com/iHtD0kPZ

Other funds locked in *waiting close* since 1 month npw
funding txid: 6b64aca2b00826b9028496552bf8bba9bc992d615bb65bc268273f92005bc2f0

**Comment by tanx** [comment] 2019-06-04 19:31
Duplicate of #1131

**Closed by tanx** 2019-06-04 19:31 UTC

**Comment by vamp111** [comment] 2019-06-05 06:03
got it, thx
