### ISSUE TITLE
Show days+hours for force closed channels in channel detail view

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/lightning-app#525] opened 2018-08-15 22:19 UTC
Atm for force closed channels we show this on the main channel page
<img width="583" alt="screen shot 2018-08-13 at 1 02 03 pm" src="https://user-images.githubusercontent.com/998190/44176224-de055080-a09d-11e8-9c11-96c11afd804a.png">

As the channel is no longer _active_ and can't be used for payments, we can probably blank out the can send/receive columns. 

When users click down in they get this: 
<img width="471" alt="screen shot 2018-08-13 at 5 03 39 pm" src="https://user-images.githubusercontent.com/998190/44176249-f83f2e80-a09d-11e8-885d-6757ef259aea.png">

As is the ID field is blank, so users are unable to lookup the txid of the closing transaction on chain. Note that this is different from the txid of the _funding_ transaction. We can get the _closing_ txid from the `ForceClosedChannel` proto: https://api.lightning.community/#forceclosedchannel

From the same proto, we can also obtain the "blocks until maturity". Atm we don't display any sort of time estimate to when the funds will be swept back into the wallet. On mainnet, this can be anxiety inducing as you don't know when the funds will be swept back into your wallet. We've received a ton of issues just related to users not quite understanding timelocks on `lnd`, which caused us to surface more info on the command line. 

To start with, we can either display the block of blocks (which at least counts down), or attempt to map the # of blocks to days+hours. One block is 10 mins, and a days worth of blocks is 144, so we can use that as a starting point from there. The goal here to give users this feedback in "dark mode", so we can set proper expectations w.r.t _when_ their funds will be restored.

**Comment by tanx** [comment] 2018-08-20 07:19
> We've received a ton of issues just related to users not quite understanding timelocks on lnd, which caused us to surface more info on the command line.

That's a good point. We should definitely surface more info here before the beta release on mainnet.

**Comment by Roasbeef** [comment] 2019-03-09 04:05
Related to this is displaying the `total_limbo_balance` field from pending channels in the dark mode channels page: https://api.lightning.community/#pendingchannels

Otherwise, if the user has only one channel, and they force close it for w/e reason, their balance on the home screen will go to zero.

**Comment by valentinewallace** [comment] 2019-03-12 23:18
@Roasbeef I can't reproduce the `closing txid` not showing: https://i.imgur.com/YTHxW29.png 

Do you know what `lightning-app` commit that screenshot was taken on?

**Comment by Roasbeef** [comment] 2019-03-13 00:46
Yeah that was back when we showed channel IDs.

**Closed** 2019-03-18 23:17 UTC
Labels: mainnet, ui
