### ISSUE TITLE
Wallet balance split over two lines

### ISSUE THREAD

**Issue by bit-the-dust** [lightninglabs/lightning-app#945] opened 2019-02-08 15:56 UTC
### Description
The large text wallet balance is split over two lines for three figure amounts like £624.50

iOS 0.0.13

### Steps to reproduce the behavior
Set fiat currency to GBP. Fund the wallet and open some channels with more than £99 value.

### Expected behavior
Channel total is displayed on a single line.

### Actual behavior
For an amount £624.50, the final zero is on a second line.

Purely cosmetic.

**Comment by tanx** [comment] 2019-02-11 06:39
Duplicate of https://github.com/lightninglabs/lightning-app/issues/879

**Closed by tanx** 2019-02-11 06:39 UTC
