### ISSUE TITLE
[alpha] Android "password failed"

### ISSUE THREAD

**Issue by tongokongo** [lightninglabs/lightning-app#1188] opened 2019-06-20 02:51 UTC
### Description
After installing, fetching the chain, one of the next consecutive try to log in using VALID PIN gives me error: "Invalid Password", vs popup "Incrrect Pin" on the REAL INCORRECT PIN. 
More in the video:
https://drive.google.com/file/d/1-OtTx-ldMKcklR-xtaBjJ11WY7cpDfQL/view?usp=sharing

### Steps to reproduce the behavior
Randomly logged in using PIN. It wasn't my first log-in using PIN to Lightning Wallet.

### Expected behavior
I should see Dashboard after "loading network" status.

### Actual behavior
There is a notification about the wrong Password

### Screenshot and/or logs if applicable
Video:
https://drive.google.com/file/d/1-OtTx-ldMKcklR-xtaBjJ11WY7cpDfQL/view?usp=sharing

**Comment by halseth** [comment] 2019-06-20 07:30
Did you try killing the app completely? (open task switcher, force quit, restart)

This looks a bit like https://github.com/lightninglabs/lightning-app/issues/1144

**Comment by modl21** [comment] 2019-06-20 12:33
I have the same issue. Force close didn't solve it. Neither did restart.

**Comment by tanx** [comment] 2019-06-20 18:21
Ok thanks for reporting. We'll look into this. Closing this as a duplicate of #967

**Closed by tanx** 2019-06-20 18:21 UTC
