### ISSUE TITLE
Feature request - to auto paste payment request / address / Lightning Addr  - ios

### ISSUE THREAD

**Issue by weaklysubjective** [lightninglabs/lightning-app#947] opened 2019-02-08 18:02 UTC
### Description
Tedious to type string , error prone. Some assistance is available (ability to paste payment request) but Connection ID (pubkey@hostIP) when creating channels has to be typed

### Steps to reproduce the behavior
create a channel
### Expected behavior
paste option ?

**Comment by tanx** [comment] 2019-02-11 06:33
Duplicate of https://github.com/lightninglabs/lightning-app/issues/911

**Closed by tanx** 2019-02-11 06:33 UTC
