### ISSUE TITLE
[Suggestion] Display node availability on channel overview screen

### ISSUE THREAD

**Issue by rstmsn** [lightninglabs/lightning-app#728] opened 2018-10-10 17:24 UTC
My transactions are failing to route, despite having 4 or 5 open channels to various nodes across the network. 
As the network stabilises, this may become less of an issue, but at this time it would be useful to have an indication as to wether or not the node associated with a particular channel is online & reachable, or not. 

An extension of this would be to include a 'last seen' timestamp. I don't know if this information is available objectively, as a feature of the network, but even a client side implementation would assist the user when it comes to pruning 'dead' nodes/channels.

**Comment by tanx** [comment] 2018-10-16 07:38
Duplicate of #505

**Closed by tanx** 2018-10-16 07:38 UTC
