### ISSUE TITLE
Recover an exiting wallet is not working in iOS

### ISSUE THREAD

**Issue by 1mdc** [lightninglabs/lightning-app#949] opened 2019-02-08 19:11 UTC
### Description
This is the first time I download and I have not created any wallet on ios device. I tried to recover my testnet wallet but it does nothing. (the button is blinking when I tab on it, but it does not do anything.)

### Steps to reproduce the behavior
1. download app
2. open and wait for the flash screen move to the next screen.
3. there are 2 options (1) new wallet or (2) recover an existing wallet.
4. select recover
5. tab "Next" button, but nothing happens

### Expected behavior
I expect it asks me seed words after tab on "Next"

### Actual behavior
Nothing happens

### Screenshot and/or logs if applicable
![img_cd5e158059aa-1](https://user-images.githubusercontent.com/5703525/52500097-085f4300-2bd5-11e9-9be9-a82cc523cde2.jpeg)

**Comment by tanx** [comment] 2019-02-11 06:27
Duplicate of https://github.com/lightninglabs/lightning-app/issues/902

**Closed by tanx** 2019-02-11 06:27 UTC
