### ISSUE TITLE
Error: panic: Rollback failed

### ISSUE THREAD

**Issue by fresheneesz** [lightninglabs/lightning-app#32] opened 2017-10-14 02:48 UTC
On windows 8.1:

```
lnd Error: panic: Rollback failed: truncate C:\Users\fresheneesz\AppData\Local\Lnd\data\testnet3\bitcoin\reg_filter_headers.bin: Access is denied. goroutine 28 [running]:
lnd Error: github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).handleHeadersMsg(0xc0424d42a0, 0xc042166bb0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:1085 +0x1d3a github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).blockHandler(0xc0424d42a0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:347 +0x434 created by github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).Start /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:200 +0x11b
```

**Comment by fresheneesz** [comment] 2017-10-14 02:49
Reopening the client, I get the error again. Here are all the logs from the start of the application:

```
lnd: 2017-10-13 19:48:29.671 [WRN] LTND: open ../lnd.conf: The system cannot find the file specified.
lnd: 2017-10-13 19:48:29.690 [INF] LTND: Version 0.3.0-alpha
lnd: 2017-10-13 19:48:29.708 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
lnd: 2017-10-13 19:48:29.721 [INF] LTND: Primary chain is set to: bitcoin
lnd: 2017-10-13 19:48:29.979 [INF] BTCN: Loaded 1723 addresses from file 'C:\Users\fresheneesz\AppData\Local\Lnd\data\testnet3\bitcoin\peers.json'
lnd: 2017-10-13 19:48:30.001 [INF] CMGR: 1 addresses found from DNS seed testnet-seed.bluematt.me
lnd: 2017-10-13 19:48:30.009 [INF] BTCN: New valid peer 165.227.7.29:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
lnd: 2017-10-13 19:48:30.010 [INF] BTCN: Syncing to block height 1210178 from peer 165.227.7.29:18333
lnd Error: panic: Rollback failed: truncate C:\Users\fresheneesz\AppData\Local\Lnd\data\testnet3\bitcoin\reg_filter_headers.bin: Access is denied. goroutine 66 [running]: github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).handleHeadersMsg(0xc04219a2a0, 0xc0422e2250) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:1085 +0x1d3a github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).blockHandler(0xc04219a2a0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:347 +0x434 created by github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).Start /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:200 +0x11b
```

**Comment by bryanvu** [comment] 2017-10-14 04:21
@aakselrod this looks to be a neutrino thing. Could you take a look?

**Comment by aakselrod** [comment] 2017-10-15 03:34
This is a duplicate of https://github.com/lightninglabs/neutrino/issues/21

**Comment by bryanvu** [comment] 2017-10-20 23:03
Thanks @fresheneesz. @aakselrod has fixed this and we can test in the next rev of the app when we push it out.

**Comment by Roasbeef** [comment] 2017-11-02 23:39
Fixed by https://github.com/lightninglabs/neutrino/pull/24

Closing.

**Closed** 2017-11-02 23:40 UTC
