### ISSUE TITLE
Swipe gesture pops home screen back to loading spinner

### ISSUE THREAD

**Issue by cfromknecht** [lightninglabs/lightning-app#978] opened 2019-02-14 12:59 UTC
iOS 12.1.4, App Version 0.15

### Description
From the home page, popping the main view with a swipe gesture returns the view to the "Loading network..." spinner. If the user releases the swipe, there is no way to get back to the home page without force restarting the application.

### Steps to reproduce the behavior
From the home screen, swipe from left to right as if doing a native back gesture and release.

### Expected behavior
The home screen would somehow be the primary view instead of a detail.

### Actual behavior
Home screen is a detail view that the swipe gesture pops.

**Comment by tanx** [comment] 2019-02-19 06:20
Duplicate of https://github.com/lightninglabs/lightning-app/issues/981

**Closed by tanx** 2019-02-19 06:20 UTC
