### ISSUE TITLE
iOS iPhone - Payments always fail.

### ISSUE THREAD

**Issue by FontaineDenton** [lightninglabs/lightning-app#955] opened 2019-02-11 01:26 UTC
### Description
Trying to pay invoice on iPhone by scanning QR code on https://starblocks.acinq.co results in failed payment.
### Steps to reproduce the behavior
Try to purchase a coffee on starblocks and scan the invoice.
### Expected behavior
Smooth quick payment to go through.
### Actual behavior
Buggy screen UI where after trying to process the payment it loops back to the invoice amount display and payment fails.
### Screenshot and/or logs if applicable
![img_6965](https://user-images.githubusercontent.com/30832395/52542847-f6e98700-2dde-11e9-87ec-9080c0e3481f.PNG)
![img_6966](https://user-images.githubusercontent.com/30832395/52542849-f6e98700-2dde-11e9-8183-e1f9a2182000.PNG)
![img_6968](https://user-images.githubusercontent.com/30832395/52542850-f7821d80-2dde-11e9-8d9f-76f0f5ba0047.PNG)
![img_6969](https://user-images.githubusercontent.com/30832395/52542851-f7821d80-2dde-11e9-9db2-8af102ea5914.PNG)
![img_6970](https://user-images.githubusercontent.com/30832395/52542852-f81ab400-2dde-11e9-83f7-239b62b3320b.PNG)

**Comment by tanx** [comment] 2019-02-11 04:14
Thanks. This is likely caused by poor routing node liquidity/availability on testnet. We're working towards improving that for the mainnet release. Closing this for now.

**Closed by tanx** 2019-02-11 04:14 UTC

**Comment by FontaineDenton** [comment] 2019-02-11 13:20
FWIW it works now, have bought many blockachinos! Love the app.
