### ISSUE TITLE
Trying to syncronize lightning app 

### ISSUE THREAD

**Issue by bitcoinuser** [lightninglabs/lightning-app#557] opened 2018-08-25 23:32 UTC
Stopped with this error:

[20:29:30.602] [info] Syncing to chain ... block height: 1409584
[20:29:30.906] [info] lnd: 2018-08-25 20:29:30.905 [INF] BTCN: Verified 10000 filter headers in the last 11.76s (height 701001, 2016-02-14 04:33:50 -0200 -02)

[20:29:30.912] [error] lnd Error: panic: couldn't write cfheaders msg: attempt to write cfheaders out of order

goroutine 1072 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders.func1(0xc4200d6640, 0x11ac720, 0xc4220a57d0, 0x11ac4e0, 0xc422134e40, 0x501)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:873 +0xb2e
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*ChainService).queryBatch(0xc420336000, 0xc4205f4000, 0x581, 0x581, 0xc4205d5e40, 0xc42055eba0, 0x0, 0x0, 0x0)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/query.go:392 +0xa3c
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders(0xc4202f0420, 0xc4205ee000, 0x581, 0x581, 0xc4200c80f8, 0x500)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:776 +0x8d2

[20:29:30.914] [error] lnd Error: github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).cfHandler.func2(0xc421661390, 0xc4202f0420, 0x15822d, 0xc42056f4c0, 0x11ab800, 0x1104428)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:500 +0x3b6
created by github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).cfHandler
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:440 +0x402

[20:29:30.948] [info] Transactions update: [object Object]
[20:29:30.949] [info] Invoices update: [object Object]
[20:29:33.606] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }

**Comment by tanx** [comment] 2018-08-27 10:42
Looks like a duplicate of: https://github.com/lightninglabs/lightning-app/issues/511#issuecomment-412781593

**Closed by tanx** 2018-08-27 10:42 UTC
