### ISSUE TITLE
Failure to open channel, missing sats

### ISSUE THREAD

**Issue by Ograf08** [lightninglabs/lightning-app#1113] opened 2019-05-12 19:48 UTC
### Description
 I sent some sats on my lightning wallet's address on mainnet, which automatically opened a channel. I later send additional funds, and three more channels were opened automatically. Now only the three channels are open, the first one doesn't seem to work and the corresponding amount does not appear in my balance. It seems that the first transaction to send sats to a channel was treated a payment and not a channel opening. I was using 0.5.0 alpha.3479 on macos, have since updated to 0.51.

Transaction ID for missing balance:
1ddc5c52d61ce3af1c3588aaef7d298341d795b8508d1290a0199fa9860372a8

### Steps to reproduce the behavior
<img width="1118" alt="Screenshot 2019-05-13 09 31 47" src="https://user-images.githubusercontent.com/50555812/57603510-36507c80-7562-11e9-996a-eb2b3e7fc016.png">
<img width="1093" alt="Screenshot 2019-05-13 09 32 42" src="https://user-images.githubusercontent.com/50555812/57603513-3781a980-7562-11e9-85c4-692dc27bc35c.png">

**Comment by tanx** [comment] 2019-06-03 22:04
Does this issue persist in `v0.5.2-alpha`?

**Comment by tanx** [comment] 2019-06-11 00:26
Seems like this is a duplicate of #1074

**Closed by tanx** 2019-06-11 00:26 UTC
Labels: bug, lnd
